# Generated by Django 5.1.2 on 2024-11-19 08:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupabaseUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'auth"."users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestModels2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('ass_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('assistan_name', models.CharField(default='Assistant', max_length=255)),
                ('subject', models.CharField(default='Default Subject', max_length=255)),
                ('teacher_instructions', models.TextField(default='Default instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user_id', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.supabaseuser')),
            ],
            options={
                'verbose_name_plural': 'Assistants',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('convo_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('prompt', models.TextField(default='Hello')),
                ('content', models.TextField(default='How are you?')),
                ('content_type', models.CharField(default='text', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('ass_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.assistant')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.supabaseuser')),
            ],
        ),
        migrations.CreateModel(
            name='TestModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('password', models.TextField()),
                ('test_user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.supabaseuser')),
            ],
        ),
    ]
