# Generated by Django 5.1.3 on 2024-11-29 09:58

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_pdfdocument_assistant_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfdocument',
            name='chunk_content',
        ),
        migrations.RemoveField(
            model_name='pdfdocument',
            name='vector_embedding',
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdf_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField()),
                ('vector_embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='users.pdfdocument')),
            ],
        ),
    ]
