# Generated by Django 5.1.2 on 2024-11-19 09:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_conversation_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='users.supabaseuser'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='users.supabaseuser'),
        ),
        migrations.AlterField(
            model_name='testmodels',
            name='test_user',
            field=models.ForeignKey(db_column='user_id', default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='users.supabaseuser'),
        ),
        migrations.CreateModel(
            name='AnonConvo',
            fields=[
                ('anonconvo_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.ForeignKey(db_column='user_id', default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='users.supabaseuser')),
            ],
        ),
    ]
