# Generated by Django 5.1.3 on 2024-11-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_pdfdocument_chunk_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='description',
            field=models.TextField(blank=True, default='Description', null=True),
        ),
        migrations.AddField(
            model_name='assistant',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
