# Generated by Django 5.1.3 on 2024-12-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_assistant_name_alter_assistant_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantrating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assistantrating',
            name='rating',
            field=models.DecimalField(choices=[(0.0, 0.0), (0.5, 0.5), (1.0, 1.0), (1.5, 1.5), (2.0, 2.0), (2.5, 2.5), (3.0, 3.0), (3.5, 3.5), (4.0, 4.0), (4.5, 4.5), (5.0, 5.0)], decimal_places=1, default=5.0, max_digits=2),
        ),
    ]
