# Generated by Django 5.1.2 on 2024-11-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='assistan_name',
            field=models.CharField(blank=True, default='Assistant', max_length=255),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='subject',
            field=models.CharField(blank=True, default='Default Subject', max_length=255),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='teacher_instructions',
            field=models.TextField(blank=True, default='Default instructions'),
        ),
    ]
