# Generated by Django 5.1.2 on 2024-11-27 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_assistant_assistan_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistant',
            old_name='ass_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='assistant',
            old_name='assistan_name',
            new_name='name',
        ),
    ]
