# Generated by Django 5.1.3 on 2024-12-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_assistantrating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
