# Generated by Django 5.1.3 on 2024-12-05 10:07

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_assistant_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=2000, validators=[django.core.validators.URLValidator()]), blank=True, default=list, null=True, size=None),
        ),
    ]
