# Generated by Django 5.1.4 on 2024-12-09 09:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_subject_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='interactions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=2000), blank=True, default=list, null=True, size=None),
        ),
    ]
