# Generated by Django 5.1.4 on 2024-12-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_assistant_interactions_alter_pdfdocument_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='interactions',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
