# Generated by Django 5.1.4 on 2024-12-12 12:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_assistant_interactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='total_reviews',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=3),
        ),
    ]
