# Generated by Django 5.1.4 on 2024-12-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_assistant_total_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assistant_images/'),
        ),
    ]
