# Generated by Django 5.1.4 on 2025-01-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_assistant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
