# Generated by Django 5.1.3 on 2024-11-29 16:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_remove_pdfdocument_chunk_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('prompt', models.TextField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('conversation_id', models.UUIDField(default=uuid.uuid4)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.assistant')),
                
                
            ],
        ),
    ]
