# Generated by Django 5.1.2 on 2024-11-28 13:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('prompt', models.TextField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('conversation_id', models.UUIDField(default=uuid.uuid4)),
                ('assistant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.assistant')),
                ('users_id', models.ForeignKey(db_column='users_id', default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='users.supabaseuser')),
            ],
        ),
    ]
