# Generated by Django 5.1.2 on 2024-11-21 13:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_delete_conversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('convo_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('prompt', models.TextField(default='Hello')),
                ('content', models.TextField(default='How are you?')),
                ('content_type', models.CharField(default='text', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('ass_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.assistant')),
                ('user_id', models.ForeignKey(db_column='user_id', default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='users.supabaseuser')),
            ],
        ),
    ]
