# Generated by Django 5.1.3 on 2024-11-29 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistantchat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='assistant',
            field=models.ForeignKey(db_column='assistant_id', on_delete=django.db.models.deletion.CASCADE, to='users.assistant'),
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='assistant',
            new_name='assistant_id',
        ),
    ]
