# Generated by Django 5.1.2 on 2024-11-26 11:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistantchat', '0002_rename_convo_id_conversation_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='ass_id',
        ),
        migrations.AddField(
            model_name='conversation',
            name='assistant_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
