# Generated by Django 5.1.4 on 2024-12-09 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistantchat', '0004_remove_conversation_user_conversation_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Conversation', 'verbose_name_plural': 'Conversations'},
        ),
    ]
