# Generated by Django 5.1.4 on 2025-02-03 14:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistantchat', '0006_knowledgeassessment'),
        ('users', '0019_alter_assistant_total_reviews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantNotes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('assistant_id', models.ForeignKey(db_column='assistant_id', on_delete=django.db.models.deletion.CASCADE, to='users.assistant')),
                ('user_id', models.ForeignKey(db_column='user_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
