# Generated by Django 5.1.4 on 2025-02-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistantchat', '0007_assistantnotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantnotes',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
